- README.rst
The example in the README currently does not work.
I propose a fix based on how you import DiCE helpers in the notebook: https://hub.gke.mybinder.org/user/microsoft-dice-smcs07gl/notebooks/notebooks/DiCE_getting_started.ipynb
> fixes README example

- dice_ml/dice_interfaces/dice_pytorch.py
- dice_ml/dice_interfaces/dice_tensorflow1.py
- dice_ml/dice_interfaces/dice_tensorflow2.py
- tests/conftest.py
- tests/test_data.py
- tests/test_data_interface/test_private_data_interface.py
- tests/test_data_interface/test_public_data_interface.py
- tests/test_dice.py
- tests/test_dice_interface/test_dice_pytorch.py
- tests/test_dice_interface/test_dice_tensorflow.py
- tests/test_model.py
- tests/test_model_interface/test_keras_tensorflow_model.py
- tests/test_model_interface/test_pytorch_model.py
> DiCE tests

- .github/workflows/pythonpackage.yml
- setup.py
This should help with running tests. And separately a minor URL change with setup.py
> Update GitHub workflows with ipython and setup.py with new url

- dice_ml/data_interfaces/private_data_interface.py
- tests/conftest.py
- tests/test_data_interface/test_private_data_interface.py
- tests/test_dice_interface/test_dice_pytorch.py
- tests/test_dice_interface/test_dice_tensorflow.py
1. Updated private data class to work with py<=3.6 using OrderedDict
2. Updated conftest.py and other tests accordingly
3. removed a redundant fixture
> Fixing private data arguments and updating tests

- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
moved sparsity enhancement method to ExplainerBase for common use by any explainer methods.
> make sparsity enhancement common in explainer base

- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
1. includes related updates to data object
2. introduced binary search as a method for sparsity enhancement
> updating data methods and adding binary search post-hoc sparsity operation

- tests/test_dice_interface/test_dice_pytorch.py
updating pytest scripts based on recent dice pytorch changes
> Update test_dice_pytorch.py based on updated dice pytorch

- dice_ml/explainer_interfaces/dice_pytorch.py
update hinge loss formulation consistent with TensorFlow version
> update hinge loss formulation in dice_pytorch.py

- dice_ml/data_interfaces/private_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/model_interfaces/base_model.py
- dice_ml/model_interfaces/keras_tensorflow_model.py
- dice_ml/model_interfaces/pytorch_model.py
- docs/_static/jquery-3.2.1.js
- docs/_static/jquery-3.4.1.js
- docs/_static/jquery-3.5.1.js
1. Added support to return k closest points from the dataset using a KD Tree
2. Added method in public_data_interface.py to predict the model on the entire dataset (required for KD tree implementation)
3. Added method in public_data_interface.py to predict the model on append the predictions to a copy of the dataset (required for KD tree implementation)
> Added KDTree method to generate cfs

- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
Updated dice_tensorflow*.py and dice_pytorch.py to generate diverse CF using RandomInitCF. While this worked in the beginning, the code got broke in between due to other changes with backup_cfs. Fixed them now.
Also, updated sparsity correction methods to not do sparsity correction if CFs are not valid.
> Changes to make RandomInitCF work for multiple CFs

- dice_ml/data_interfaces/private_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/explainer_interfaces/feasible_base_vae.py
- dice_ml/model_interfaces/base_model.py
- docs/source/notebooks/DiCE_model_agnostic_CFs.ipynb
- tests/test_data.py
- tests/test_dice_interface/test_dice_pytorch.py
- tests/test_dice_interface/test_dice_tensorflow.py
- Shifted generic code to explainer_base
- Removed tf specific computations in loss computation
- Added support for label encoding
- Obtained diverse counterfactuals through genetic algorithm
- Made dice_KD work without tensorflow models
- Updated documentation for dice_genetic in DiCE_model_agnostic_CFs.ipynb
> Dice genetic

- dice_ml/data_interfaces/private_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/explainer_base.py
- Refactored code when 0 valid counterfactuals are found
- Implemented features_to_vary in DiceKD with the parameter training_points_only
- Fixed random init merge error
> Dice kd features to vary

- dice_ml/data_interfaces/private_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
- docs/source/notebooks/DiCE_with_advanced_options.ipynb
- tests/test_data.py
- Added features to vary in dice_genetic
- Added permitted_range in dice_genetic
- Cleaned up permitted_range code
> Added features to vary & permitted range in dice_genetic

- dice_ml/explainer_interfaces/dice_genetic.py
- Modified predict function and loss to account for multiclass classification
> Extended genetic algorithm to multiclass

- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- Extended dice_KD to multiclass
- did error checking for desired class values in genetic and KD
> Extended dice_KD to multiclass

- dice_ml/dice.py
- docs/source/notebooks/Benchmarking_different_CF_explanation_methods.ipynb
- docs/source/notebooks/DiCE_getting_started.ipynb
Simple fix to allow a `method` parameter when calling DiCE, that allows any method to called. 
Example in benchmarking notebook.
> kdtree and genetic methods can be called from dice

- dice_ml/dice.py
- dice_ml/model.py
- dice_ml/model_interfaces/base_model.py
- docs/source/notebooks/Benchmarking_different_CF_explanation_methods.ipynb
- docs/source/notebooks/DiCE_model_agnostic_CFs.ipynb
- Made backend = `sklearn` for sklearn models
- Updated documentation with new decide method and backend modifications
> Backend modifications for sklearn models

- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/dice.py
Tensorflow is an optional dependency now
> Remove tensorflow imports where not needed

- tests/test_data.py
- tests/test_data_interface/test_public_data_interface.py
Caution: test only public data interface for now, private data interface tests need to be added
> Updated tests for data interface based on its new fuctionality

- dice_ml/dice.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- docs/source/notebooks/DiCE_feature_importances.ipynb
Refactoring PR to carve dicerandom out of explainer_base.
> Created a new class for dice random method

- .github/workflows/pythonpackage.yml
- dice_ml/counterfactual_explanations.py
- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/utils/serialize.py
- docs/source/notebooks/DiCE_feature_importances.ipynb
- tests/test_dice_interface/test_dice_pytorch.py
- tests/test_dice_interface/test_dice_tensorflow.py
- tests/test_model_interface/test_keras_tensorflow_model.py
- tests/test_model_interface/test_pytorch_model.py
- tests/test_notebooks.py
Each notebook in `source/docs/notebooks` can be used as a smoke test.
> Added file to run all notebooks as a test

- dice_ml/explainer_interfaces/dice_KD.py
- Refactored diceKD so that it works with the major changes
- Removed duplicates from diceKD output
- Training_points_only is always true
> DiceKD changes after transformer

- dice_ml/counterfactual_explanations.py
- tests/test_counterfactual_explanations.py
> Add minor version to counterfactual explanations

- dice_ml/explainer_interfaces/dice_KD.py
- Fixed minor bugs in Dice KD
- Implemented Permitted range in dice KD
> Fixed DiceKD bugs, implemented permitted_range

- dice_ml/counterfactual_explanations.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/utils/exception.py
- tests/test_counterfactual_explanations.py
- tests/test_dice.py
>  Add user config validation for minimum number of query instances for meaningful explanations

- dice_ml/counterfactual_explanations.py
- tests/test_counterfactual_explanations.py
Create property interface for data members in CounterfactualExplanations class to sort the local and summary importance values.
> Sort importance values in CounterfactualExplanations

- MANIFEST.in
- README.rst
> Readme and manifest file update for new release

- dice_ml/constants.py
- dice_ml/dice.py
- dice_ml/model.py
- tests/test_dice.py
- tests/test_model.py
> Move string literals to module constants

- dice_ml/counterfactual_explanations.py
- tests/test_counterfactual_explanations.py
> Add tests for sorted order summary importance and local importance

- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- docs/source/notebooks/Benchmarking_different_CF_explanation_methods.ipynb
- tests/test_dice_interface/test_dice_KD.py
- tests/test_dice_interface/test_dice_genetic.py
- Normalized proximity loss, removed proximity loss for categorical variable, added sparsity loss
- added support for total_CFs  = 0
> Normalized losses, added support for 0 cfs needed

- dice_ml/explainer_interfaces/explainer_base.py
- requirements.txt
> Add progress bar for counterfactual computation

- dice_ml/data_interfaces/public_data_interface.py
> Correct error messages in DICE public data interfaces

- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_dice_KD.py
- tests/test_dice_interface/test_dice_genetic.py
> Raise user exception when class not identified

- dice_ml/counterfactual_explanations.py
- dice_ml/diverse_counterfactuals.py
- tests/test_dice_interface/test_dice_KD.py
> Move desrialization logic from counterfactual explanations to counterfactual examples

- dice_ml/counterfactual_explanations.py
- tests/test_counterfactual_explanations.py
> Validate version in json input in counterfactual explanations

- dice_ml/utils/helpers.py
The adult dataset is large so can cause some undesirable effects if not deleted after downloading.
> Remove data file after downloading in helpers.py

- dice_ml/dice.py
- dice_ml/model.py
- tests/test_dice.py
> Add config validations dice exp interface and dice model interface

- dice_ml/data_interfaces/public_data_interface.py
- tests/test_data_interface/test_public_data_interface.py
If the data validations are not done, the runtime failures are hard to debug. Hence, the validations on continuous_features and permitted_ranges.
> Add more validations public_data_interface.py

- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- tests/conftest.py
- tests/test_dice_interface/test_explainer_base.py
> added userconfig exception for totalcfs<1

- .github/workflows/pythonpackage.yml
- requirements-test.txt
> Create a requirements file for test dependencies

- .github/workflows/pythonpackage.yml
- requirements-test.txt
> Add code coverage report to tests

- .github/workflows/pythonpackage.yml
> Add OS specific build to PR gate

- .github/workflows/pythonpackage.yml
Reverts interpretml/DiCE#141
Seems like windows build has some tensorflow issue.
> Limiting to only Linux and MAC OS for PR gates

- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/model_interfaces/base_model.py
- dice_ml/utils/exception.py
- tests/conftest.py
- tests/test_model_interface/test_base_model.py
> Move predict_fn() in ExplainerBase

- .github/workflows/pythonpackage.yml
> Publish unit test results

- README.rst
> Fix project README

- docs/source/notebooks/DiCE_feature_importances.ipynb
- tests/test_notebooks.py
> Fail notebook tests if output present in cells

- dice_ml/counterfactual_explanations.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/model.py
Minor formatting edits: Changed `if(X)` to `if X`
> Formatting changes

- dice_ml/dice.py
- tests/test_dice.py
> User exception when kdtree explainer is configured with private data interface

- dice_ml/diverse_counterfactuals.py
> Refactor duplicate code in visualize_as_dataframe() and visualize_as_list()

- .github/workflows/pythonpackage.yml
> Dump the information about the  most time consuming tests

- docs/source/notebooks/DiCE_getting_started.ipynb
This is pertaining to issue https://github.com/interpretml/DiCE/issues/189.
> Change the query instance to be test data instead of train data

- docs/source/notebooks/DiCE_getting_started.ipynb
> Use train dataset for training dice-ml data interface

- .github/workflows/pythonpackage.yml
> Add python 3.9 to tests

- tests/test_dice_interface/test_explainer_base.py
Follow up tests for PR https://github.com/interpretml/DiCE/pull/207
> Add validation tests to dice explainers

- README.rst
> Add jsonschema to documentation

- dice_ml/schema/counterfactual_explanations_v1.0.json
- dice_ml/schema/counterfactual_explanations_v2.0.json
> Fix indentation in schema files

- docs/source/conf.py
- setup.py
The release contains the following:-
- Fix for logging
- Fix indentation in schema files
- Add documentation to save generated counterfactuals to disk
> Version bump 0.7.2 (Minor bug fixes)

- .github/workflows/python-linting.yml
- .github/workflows/pythonpackage.yml
- requirements-test.txt
The python linting steps like flake8, flake8_nb can be done once rather than with every os version and python version.
> Separate python linting and tests pipelines

- .github/workflows/python-linting.yml
- requirements-linting.txt
> Move linting packages to requirements file

- requirements-linting.txt
> Add flake8-breakpoint to avoid code checkin with active breakpoints

- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_explainer_base.py
Bubble up the desired_range value inspection so guide the user to supply the correct value.
> Add configuration validation for desired_range

- docs/source/notebooks/DiCE_multiclass_classification_and_regression.ipynb
- tests/conftest.py
- tests/test_dice_interface/test_explainer_base.py
- tests/test_model_interface/test_base_model.py
> Replace load_boston() with fetch_california_housing()

- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_random.py
Looks like pd.append() is deprecated. Thanks @giandos200 for bringing this to our attention.
> Replace pd.append() with pd.concat()

- .github/workflows/code-scan.yml
- .github/workflows/python-linting.yml
- .github/workflows/python-package-conda.yml
- .github/workflows/python-publish.yml
- .github/workflows/pythonpackage.yml
> Update github action for checkout from version 2 to 3

- README.rst
Greetings!
Me and @janjagusch [forged DiCE](https://github.com/conda-forge/staged-recipes/pull/19442), making it available for install from the [conda-forge repository](https://anaconda.org/conda-forge/dice-ml).
This PR just updates the README with that information.
Cheers
> Add conda-forge install information to README

- dice_ml/counterfactual_explanations.py
- dice_ml/diverse_counterfactuals.py
> Fix variable typo

- .github/workflows/code-scan.yml
- .github/workflows/python-linting.yml
- .github/workflows/python-package-conda.yml
- .github/workflows/pythonpackage.yml
Scheduling one build for the PR gated builds everyday at 5:30am UTC time. This will help in knowing when any of the builds start failing.
> Add scheduled builds

- requirements-linting.txt
It seems that this gate started to fail with the following error:-
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.7.[14](https://github.com/interpretml/DiCE/actions/runs/3174866216/jobs/5172193863#step:6:15)/x64/bin/flake8", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
app.run(argv)
File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
self._run(argv)
File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
self.initialize(argv)
File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line …
```
> Update flake8 to 4.0.1 requirements-linting.txt to fix linting gate

- dice_ml/data_interfaces/public_data_interface.py
> Changed df.append to pd.concat to avoid pandas warning

- dice_ml/data_interfaces/private_data_interface.py
> Allowing float as numeric type for private data

- README.rst
When the sample code is executed, the following error occurs. 
```py
import dice_ml
from dice_ml.utils import helpers # helper functions
d = dice_ml.Data(dataframe=helpers.load_adult_income_dataset(),
continuous_features=['age', 'hours_per_week'],
outcome_name='income')
m = dice_ml.Model(model_path=dice_ml.utils.helpers.get_adult_income_modelpath())
exp = dice_ml.Dice(d,m)
```
```sh
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-425690f78bba>](https://localhost:8080/#) in <module>
8 m = dice_ml.Model(model_path=dice_ml.utils.helpers.get_adult_income_modelpath())
9 # DiCE explanation instance
---> 10 exp = dice_ml.Dice(d,m)
2 frames …
```
> Add input value to method

- .github/workflows/python-linting.yml
- .github/workflows/python-package-conda.yml
- .github/workflows/python-publish.yml
- .github/workflows/pythonpackage.yml
Signed-off-by: Gaurav Gupta <47334368+gaugup@users.noreply.github.com>
> Update setup-python to version 4

- tests/test_notebooks.py
Looks like the notebook returned in not used.
> Update test_notebooks.py to return only error list

- .github/workflows/notebook-tests.yml
- .github/workflows/pythonpackage.yml
- setup.py
Signed-off-by: Gaurav Gupta <47334368+gaugup@users.noreply.github.com>
> Add tests and classifier for python 3.11

- tests/conftest.py
- tests/test_counterfactual_explanations.py
- tests/test_data_interface/test_private_data_interface.py
- tests/test_data_interface/test_public_data_interface.py
- tests/test_dice_interface/test_dice_KD.py
- tests/test_dice_interface/test_dice_pytorch.py
- tests/test_dice_interface/test_dice_tensorflow.py
- tests/test_model_interface/test_keras_tensorflow_model.py
- tests/test_model_interface/test_pytorch_model.py
This will help optimize the run time of tests.
> Change the scope of pytest fixtures to be session instead of function

- .github/workflows/notebook-tests.yml
- .github/workflows/python-package.yml
- requirements-deeplearning.txt
Looks like the caching issue is resolved. So removing the "--no-cache-dir" option.
> Remove python "--no-cache-dir" option from workflow ymls

- dice_ml/explainer_interfaces/dice_xgboost.py
- dice_ml/model_interfaces/xgboost_model.py
- requirements.txt
added an interface for xgboost in the file modle_intrerfaces/xgboost_model.py as well as explainer_interfaces/dice_xgboost.py, tested the implimentation in a regressor model and it works
> Xgboost interface
