interpretml/DiCE

- dice_ml/data_interfaces/public_data_interface.py
This simple change fix a possible error when a continuous feature has the same prefix as a categorical one (`col.startswith(col_parent)` would be `True` in this case). With that small addition, this would not happen.
> Fix continuous features with similar prefix

- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
Adding an option to feed permitted range in generate_counterfactuals() method in addition to the current option of providing them only in data_interface.
> adding permitted range option to generate counterfactuals

- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- Ranked KD tree outputs in descending order of distance + lambda * sparsity
- Added verbose check in dice_genetic
> Ranked KD tree outputs by sparsity along with distance

- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/explainer_interfaces/feasible_base_vae.py
- Added `desired_range` and `model_type` in diverse_counterfactuals.py to print the correct statements. Also corrected the print statements to print the desired range as the outcome in regression problems
- Added predicted outcome to a copy of the dataframe (earlier it was adding it directly to the original dataframe)
- dice_KD now builds KD trees within generate counterfactuals (when a user supplies desired_range or desired_class)
- Handled the case when there are no instances within desired_range in the training data (KD tree is empty)
> Kd regression

- requirements-deeplearning.txt
- requirements.txt
- setup.py
These are quite big packages and may not be needed if the user needs to explain sklearn models. 
If needed, they can installed as optional dependencies using pip, `pip install dice-ml[deeplearning]`
> Move tensorflow and pytorch to optional dependencies

- dice_ml/diverse_counterfactuals.py
Ipython is not a hard dependency within dice-ml. So pushing the import where the the display function from Ipython is used. The calling of other functions in this file shouldn't be affected if someone doesn't have ipython dependency. 
> Move Ipython import inside function

- docs/source/notebooks/DiCE_multiclass_classification_and_regression.ipynb
the as_frame argument returns both X and y is one dataframe. Unfortunately for load_boston() doesn't support as_frame option.
> Move Iris dataset to as_frame in DiCE_multiclass_classification_and_regression.ipynb

- dice_ml/counterfactual_explanations.py
- tests/test_counterfactual_explanations.py
> Remove unused method and refactor tests

- dice_ml/explainer_interfaces/dice_random.py
It seems like major time while computing counterfactuals in DiceRandom class is spent in calling get_output(). Hence, reducing the number of calls to get_couput() will reduce the run time. The PR does one call to get_output() for the query point and caches the result so that it can be reused across the computation of counterfactuals for that point. This optimizes the classification scenario only for now.
> Reduce number inferences in dice random

- dice_ml/dice.py
- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_explainer_base.py
The ExplainerBase class doesn't implement _generate_counterfactuals() but expects derived classes to implement this function. Hence, making ExplainerBase class an abstract class and making the method _generate_counterfactuals() an abstract method so that the deriving class always implements it.
> Make ExplainerBase Abstract Class

- dice_ml/constants.py
- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/model.py
- dice_ml/model_interfaces/base_model.py
- tests/test_model.py
- Add user validations to dice-ml model interface to validate backend and model_type
- Reduce cyclometric complexity of is_cf_valid() to below 10.
- Add constants for 'classifier' and 'regressor'
- Added tests for validation of backend and model_type.
> Add user validations to dice-ml model interface

- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- tests/test_dice_interface/test_dice_pytorch.py
- tests/test_dice_interface/test_dice_tensorflow.py
Seems like generate_counterfactuals() in dice_tensorflow1.py,  dice_tensorflow2.py and  dice_pytorch.py return CounterfactualExamples. This has integration issues when the customers use this output to compute feature importance. Hence, changing the return type in these function to return CounterfactualExplanations.
This is related to the github issue https://github.com/interpretml/DiCE/issues/155.
> Return CounterfactualExplanations from tensorflow and pytorch explainers

- tests/test_dice_interface/test_dice_KD.py
It seems like there are no tests covering the scenario when posthoc_sparsity_algorithm is "binary" or None. Only the default option of "linear" search is tested.
> Add tests for binary posthoc_sparsity_algorithm

- dice_ml/counterfactual_explanations.py
- requirements-test.txt
- requirements.txt
> Add jsonschema as a hard dependency

- dice_ml/data_interfaces/public_data_interface.py
- tests/test_data_interface/test_public_data_interface.py
It seems like the user dataframe is corrupted as public_data_interface.py tries to change the metdata in case of categorical columns. The fix is to make a copy of data and use the copy throughout the data interface. 
> Create copy of dataframe in public_data_interface.py to avoid user data corruption

- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/utils/helpers.py
- tests/conftest.py
- tests/test_dice_interface/test_dice_KD.py
- tests/test_dice_interface/test_dice_genetic.py
- tests/test_dice_interface/test_dice_random.py
In response to #161 
- Added check to throw an error if query instance has an unknown column
- Added tests for dice_genetic, dice_KD to check if query instance has an unknown column
- Fixed bug in helpers.py - added parameter invalid_raise = True for the adult dataset
- Fixed bug in tests: query instance had categorical values not present in training data
- Added tests for dice_random
> Added checks for dice_random

- dice_ml/explainer_interfaces/explainer_base.py
- tests/conftest.py
- tests/test_dice_interface/test_dice_genetic.py
- Alerting users when they look to generate counterfactuals that they don't have target in their query instances.
-  
> Add validation to check target column in query instance

- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- docs/source/notebooks/DiCE_model_agnostic_CFs.ipynb
- tests/conftest.py
- tests/test_dice_interface/test_dice_KD.py
Signed-off-by: Soundarya Krishnan <soundaryak4898@gmail.com>
In response to issue #169 
- Made changes to show original indices of rows in the training data while displaying counterfactuals
- Added a test to ensure that this logic is being followed
- Fixed bug in dice_random when 0 cfs were being returned
> Returning original index for dice-KD

- dice_ml/explainer_interfaces/explainer_base.py
In cases when the counterfactual for a query point are not found, the local importance computation loop would fail trying to access a None object. Hence, continuing the loop in event when the counterfactuals are  not found for a query point.
> Continue feature importance computation if no counterfactuals found

- dice_ml/data_interfaces/base_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/utils/helpers.py
- tests/conftest.py
- tests/test_data_interface/test_public_data_interface.py
- tests/test_dice_interface/test_dice_genetic.py
- tests/test_dice_interface/test_explainer_base.py
In response to #168 
- Before, we were normalising by doing (value - min_value)/(max_value - min_value). Now, if min_value == max_value, setting the value to 0, according to https://stats.stackexchange.com/questions/441342/same-value-of-min-and-max-in-min-max-normalisation
- Added check to ensure that predictions aren't numpy.float32
- Added support for columns in query_instance not being in the same order as the dataset, shifted the function to base_data_interface
- Added test to check the case when min & max of a column are equal
- Added test to check that no error is raised when the outcome is not the last column
- Refactored test_dice_genetic to use generate_counterfactuals instead of _generate_counterfactuals
- Removed test_zero_cfs as an exception is raised by explainer_base
> Fixed bugs for issue 168

- dice_ml/diverse_counterfactuals.py
- dice_ml/schema/counterfactual_explanations_v2.0.json
- tests/test_counterfactual_explanations.py
It seems the serialization of counterfactual explanations fails if no counterfactuals are found. Hence, fixing this and adding tests.
> Fix serialization counterfactual explanations when no CFs found

- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_data_interface/test_public_data_interface.py
1. If we do not have these validations, we go on to generate counterfactuals with the supplied values. The supplied values may not be in the original training data.
2. Moved some data_interface checks ipublic_data_interface.py.
3. Add the tests to test these checks
> Validate feature_to_vary and perimtted_features in generate_counterfactuals()

- dice_ml/explainer_interfaces/dice_genetic.py
- tests/test_dice_interface/test_dice_genetic.py
Signed-off-by: Soundarya Krishnan <soundaryak4898@gmail.com>
- Population size is now set to 10* total_CFs
- If the `rest_members` variable somehow becomes negative, we raise a SystemError exception to be more informative to the user
> Fixed negative dimension issue

- dice_ml/explainer_interfaces/explainer_base.py
- tests/conftest.py
- tests/test_dice_interface/test_explainer_base.py
It seems if  user declares a numeric valued column as categorical, the dice-ml public_data_interface.py converts it into strings. However, at the time of CF generation, the value in the query instance of that feature is matched as is with the tring values which results in ValueError. 
The solution is the convert the feature value to string and compare against the learned categories.
> Extend categorical value check to numeric values

- README.rst
Seems like a significant dice-ml users request for some way to save the counterfactuals on disk as a .csv file. Hence adding some sample code to the project README.
> Add documentation to save generated counterfactuals to disk

- dice_ml/data_interfaces/private_data_interface.py
Discovered via [an import of the `responsibleai` package](https://github.com/microsoft/responsible-ai-widgets/issues/850), a library package shouldn't call `logging.basicConfig()`. That logging call is [really only meant to be called once per process](https://docs.python.org/3/library/logging.html#logging.basicConfig):
> This function does nothing if the root logger already has handlers configured, unless the keyword argument force is set to True.
If a user calls `logging.basicConfig()` after `import dice_ml`, they probably aren't going to get the log messages they expect.
Signed-off-by: Richard Edgar <riedgar@microsoft.com>
> Fix for logging

- dice_ml/explainer_interfaces/explainer_base.py
It seems desired_class is cast to numpy.float32 which is not JSON serializable. Hence, casting the desired_class to int() to make sure that the to_json() on CounterfactualExplanation class is successful.
> Cast desired_class to int() to fix counterfactual serialization

- requirements-deeplearning.txt
It seems torchvision is not used in any dice-ml module.
> Remove torchvision from deeplearning dependencies

- dice_ml/explainer_interfaces/dice_KD.py
> Fix failure in dice_kdtree.py due to undefined variable

- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_explainer_base.py
It seems the generate_counterfactuals() method in dice_genetic.py support many more arguments than the ones supported in  generate_counterfactuals()  in explainer_base.py. Adding the additional parameters to generate_counterfactuals()  in explainer_base.py.
> Add additional parameters to generate_counterfactuals() function

- .github/workflows/pythonpackage.yml
It seems that python 3.6 is not available on MAC now.
Run actions/setup-python@v1
Error: Version 3.[6](https://github.com/interpretml/DiCE/runs/5048471967?check_suite_focus=true#step:3:6) with arch x64 not found
Available versions:
3.10.2
3.[7]
3.[8]
3.[9]
> Update pythonpackage.yml to skip macos test for python 3.6

- .github/workflows/pythonpackage.yml
- requirements-deeplearning.txt
- setup.py
- tests/test_notebooks.py
Add tests for python 3.10. We need to skip the notebooks that use torch models as there is no release for torch on 3.10. 
> Add tests and classifier for python 3.10

- .github/workflows/pythonpackage.yml
This fixes the issue where the python PR gate was failing during upload of unit test results for python 3.6. Now limiting test result upload and code coverage upload for linux build with python 3.8.
> Update pythonpackage.yml to limit one test result upload and one code coverage upload

- requirements-linting.txt
It seems like the linting gate is broken with the following error:-
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line [15](https://github.com/interpretml/DiCE/runs/5875796175?check_suite_focus=true#step:6:15)7, in load_plugin
self._load()
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 134, in _load
self._plugin = self.entry_point.load()
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
module = import_module(match.group('module'))
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/importlib/__init__.py", line 127, in import_module
return …
```
> add 'packaging' to requirement-linting.txt to fix broken linting gate

- dice_ml/explainer_interfaces/dice_tensorflow1.py
> Change num_ouput_nodes to num_output_nodes in dice_tensorflow1.py

- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_explainer_base.py
This came up in testing that if the features_to_vary is empty list then the counterfactual computation fails eventually. Raising this as an exception condition.
> Raise user config validation exception when features_to_vary list is empty

- dice_ml/explainer_interfaces/dice_KD.py
Fixes #303 by reordering the columns of ``query_instance_df_dummies`` so that the resulting array has the same format as ``data_df_copy`` in the KD-tree.
> Fix #303 - Reorder columns in query instance

- dice_ml/explainer_interfaces/explainer_base.py
Previously, ``original_pred`` was always converted from a class score vector to a class by taking the ``np.argmax`` in the function``infer_target_cfs_class``. This causes issues when ``original_pred`` is not a vector and already only contains the predicted class. In this case, ``original_pred`` is either a scalar or a size 1 array, for both of which ``np.argmax`` always returns 0. Therefore, in these cases the function always returns ``target_class = 1``, regardless of the original prediction.
I have fixed this by only converting ``original_pred`` when it is an array with a size greater than 1. The function must remain flexible for both vector-type ``original_pred`` and scalar-type ``original_pred`` because three classes (``dice_random``, ``dice_genetic`` and ``dice_kd``) depend on the …
> Fix #215 - Only convert original_pred if necessary

- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_pytorch.py
- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/dice_tensorflow1.py
- dice_ml/explainer_interfaces/dice_tensorflow2.py
- dice_ml/explainer_interfaces/explainer_base.py
For some cases defined in issue #46, DiCE enters in an infinite loop because of very small changes in the do_linear_search function. This commit fixes that by adding an upper limit for linear search.
> fix #46 - Implement steps limit for linear search

- requirements-test.txt
- requirements.txt
Seems like the newer release of scikit-learn 1.1.2 led to failure of PR gates. Hence pinning the scikit-learn to less than 1.1.2 in test dependencies. 
Signed-off-by: Gaurav Gupta <47334368+gaugup@users.noreply.github.com>
> Update requirements-test.txt to pin scikit-learn to below 1.1.2

- .github/workflows/code-scan.yml
- .github/workflows/python-linting.yml
- .github/workflows/python-package-conda.yml
- .github/workflows/pythonpackage.yml
> update branchname from master to main in ci workflows

- dice_ml/data_interfaces/base_data_interface.py
- dice_ml/data_interfaces/private_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
This is a modification to unify the type comparison method.
Previously, there were two methods
- `if type(ABC) is str:`
- `if isinstance(ABC, str):`
This fix is related to coding and does not affect services. However, this unification is expected to increase code maintainability during development.
> Use isinstance() rather than type() for a typecheck.
> reference : https://pycodequ.al/docs/pylint-messages/c0123-unidiomatic-typecheck.html
> Fix to unify type comparison methods

- dice_ml/explainer_interfaces/feasible_base_vae.py
- dice_ml/explainer_interfaces/feasible_model_approx.py
Signed-off-by: Daiki Katsuragawa <50144563+daikikatsuragawa@users.noreply.github.com>
--
As part of #331, the verification detected mypy error other than a type hint. This occurs when the variable name `train_x` is used as a variable of another type. Fortunately, there is no other place where this error occurs. Since this is not the intent of #331, we have created a pull request on its own. The command and output that detected this error is as follows.
```sh
mypy --ignore-missing-imports --disallow-untyped-def dice_ml/
```
```sh
(skip)
dice_ml/explainer_interfaces/feasible_model_approx.py:110: error: No overload variant of "__getitem__" of "tuple" matches argument type "Tuple[slice, Any]"
dice_ml/explainer_interfaces/feasible_model_approx.py:110: note: Possible overload variants: …
```
> Fix variable name

- dice_ml/explainer_interfaces/explainer_base.py
fixed #342 . Now `do_posthoc_sparsity_enhancement`, `do_linear_search` and `do_binary_search` correctly calculate `diff` between `query_instance` and `final_cfs_sparse`.
> fix int(final_cfs_sparse.at[cf_ix, feature])

- environment.yml
- requirements.txt
It seems like h5py is not used as a required package in dice-ml.
Signed-off-by: Gaurav Gupta <47334368+gaugup@users.noreply.github.com>
> Update requirements.txt to remove h5py

- requirements-test.txt
- requirements.txt
Following python packages need to be pinned:-
1. Looks like `pandas` had a new major release which breaks the tests. Pinning pandas to below 2.0.0 as a result.
> Update requirements.txt to pin pandas below 2.0.0

- dice_ml/data_interfaces/public_data_interface.py
- tests/test_data_interface/test_public_data_interface.py
This is to make sure we cover more integer and float types and don't raise error.
> Update public_data_interface.py to add more numpy int and float types

- dice_ml/utils/helpers.py
- tests/test_helpers.py
Looks like the URL https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data gives 404. The URL that works is https://archive.ics.uci.edu/static/public/2/adult.zip.
> Change logic to get the adult dataset

- .github/workflows/notebook-tests.yml
- .github/workflows/python-package.yml
- requirements-deeplearning.txt
Builds are failing for multiple reasons
1) Looks like the builds on MAC OS with python 3.7 are failing with the following error:-
```
ImportError while loading conftest '/Users/runner/work/DiCE/DiCE/tests/conftest.py'.
tests/conftest.py:4: in <module>
import pandas as pd
../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/__init__.py:50: in <module>
from pandas.core.api import (
../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/api.py:48: in <module>
from pandas.core.groupby import (
../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/groupby/__init__.py:1: in <module>
from pandas.core.groupby.generic import (
../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/groupby/g …
```
> Fix failing builds and skipping MACOS tests

- dice_ml/diverse_counterfactuals.py
Previously, `show_only_changes `used direct equality, resulting in all values flagging as changed incorrectly.
This change updates CounterfactualExamples to use `math.isclose` to generate both the lists and displayed dataframes when `show_only_changes=True`
> Updated display_df and print_list to use isclose for show_only_changes

- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_explainer_base.py
Looks like missing values in query instances cause weird failures when attempting to do predict()/predict_proba(). Hence, asking the user to impute the values for missing values.
> Raise user error when any of the query instances has missing values

- dice_ml/counterfactual_explanations.py
- dice_ml/diverse_counterfactuals.py
- dice_ml/explainer_interfaces/dice_KD.py
- dice_ml/explainer_interfaces/dice_genetic.py
- dice_ml/explainer_interfaces/dice_random.py
- dice_ml/explainer_interfaces/explainer_base.py
- dice_ml/utils/helpers.py
- tests/conftest.py
- tests/test_dice_interface/test_dice_KD.py
- tests/test_dice_interface/test_dice_genetic.py
- tests/test_dice_interface/test_dice_random.py
Fixes #369.
Only supported for sklearn models since pytorch/tf models cannot accept non-numeric labels.
> Return original class labels without encoding

- dice_ml/data_interfaces/base_data_interface.py
- dice_ml/data_interfaces/private_data_interface.py
- dice_ml/data_interfaces/public_data_interface.py
- dice_ml/explainer_interfaces/explainer_base.py
- tests/test_dice_interface/test_explainer_base.py
Explainer methods perform different operations that may result in a different type for the output features in a CF (some of these are required). 
To ensure consistency, this PR adds a type consistency operation before returning the CFs.
> Ensure same type for CF output as the input features

- .github/workflows/python-publish.yml
Package upload failed using username/password as PyPI has shifted to 2FA.
They recommend setting up trusted publisher: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
This PR setups the publisher.
> updating package publish workflow due to 2FA used by PyPI

- .github/workflows/python-package.yml
It seems the we need the secret to upload the code coverage which we don't have it. Disabling uploading of code coverage until we have a way to upload the code coverage.
> Update python-package.yml to comment out upload of code coverage report to codecov
